<?php
/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.

* function erb_preprocess_html(&$variables) {
*   if ($node = \Drupal::request()->attributes->get('node')) {
*     $variables['attributes']['class'][] = 'page-node-' . $node->id();
 *  }
 *   $current_path = \Drupal::service('path.current')->getPath();
 *  $variables['current_path'] = \Drupal::service('path.alias_manager')->getAliasByPath($current_path);
* }
 */